<a href="https://colab.research.google.com/github/19pa1a0436/DAMU.SAIKIRAN/blob/master/daamu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x=np.arange(start=1,stop=10).reshape(3,3)
print(x[1,1])

5


In [3]:
print(x[1:3])

[[4 5 6]
 [7 8 9]]


In [4]:
print(x[2:3])

[[7 8 9]]


In [6]:
print(x[:,1:3])

[[2 3]
 [5 6]
 [8 9]]


In [7]:
print(x[1:,1:])

[[5 6]
 [8 9]]


In [8]:
print(x[1:3,1:3])

[[5 6]
 [8 9]]


In [9]:
print(x[1:])

[[4 5 6]
 [7 8 9]]


In [10]:
print(x[1,1])

5


In [11]:
print(x[1])

[4 5 6]
